/**
 * Cabra Judo Club - Native Blog & Newsfeed Data
 * 100% Native, self-hosted, zero 3rd-party dependencies.
 */
export const blogPosts = [
  {
    "id": "e6f212a4-7f12-4c91-9c88-123456789abc",
    "title": "Q&A with Niall Wynn, Founder of Proper Order Coffee",
    "intro": "We sat down with Niall Wynn, judoka and founder of Proper Order Coffee Co., to discuss his journey from swimming to judo.",
    "category": "Club News",
    "date": "2026-09-25",
    "dateFormatted": "2026-09-25",
    "author": "Cabra Judo",
    "featuredImage": "images/niall_wynn.png",
    "featured": true,
    "content": "<p><strong>What brought you to Judo?</strong></p><p>I did a little bit of Judo as a teenager and really enjoyed it but at the time swimming was my main focus. I had already represented Ireland in the swimming pool and wanted to see where it would take me.</p><p>The reason I decided to come back to Judo was that it was something I had enjoyed and felt like exploring more. Swimming was great and I do still enjoy it but I feel like I've more to learn about in the Judo world than the swimming world which is exciting.</p><p><strong>How does it compare to swimming?</strong></p><p>Like swimming, Judo is primarily an individual sport but there is a real team spirit in both sports. There's a desire to help one another as well as lift those around you and that is something I've always enjoyed.</p><p><strong>How does Judo help with running a business?</strong></p><p>As for running, I hate it. Judo is a great escape from the daily grind of running the businesses. Being able to switch off the noise of the day and concentrate on whats happening on the tatami is a great help when trying to find balance.</p><p>Finding a routine was hard at first but once you do, its great and something I really look forward to each week now.</p><p><strong>Looking at your life right now, what is the single biggest thing judo has given back to you since returning—is it physical fitness, mental resilience, or simply the joy of mastering a difficult skill or getting to do something fun with your kids?</strong></p><p>Bruce actually started back at Judo before I did. When I saw how much he was enjoying himself it really pushed me to do it too.</p><p>The thing I've enjoyed the most since returning is the challenge of being a bit better every day. It was something I enjoyed about swimming and the opportunity be better and to challenge myself in Judo comes up almost weekly.</p><p><strong>Martial arts clubs have a distinct sense of camaraderie where rank and background melt away once you start randori (sparring). What has the local judo community meant to you since joining back up?</strong></p><p>I've really enjoyed the club ethos since returning.</p><p>The atmosphere of support is fantastic, especially for the 'elder' Judokas like myself. My fellow Judokas and coaches are more interested in helping me learn and progress rather than throwing me up in the air, which has been very refreshing and made me want to keep coming back.</p><p><strong>What would you say to other parents or former competitive athletes who feel hesitant or \"too old/out of shape\" to step back into a martial arts club after a long break?</strong></p><p>The club has been great at getting me moving again.</p><p>At the beginning it was tough but everybody was always very encouraging. The coaches and players always helped me to push myself when I needed to and take it easy in myself when I needed it as well</p><p>It was very much slow and steady at the start but after a while the progress started to feel great. I'm able to physically push myself again which is a great feeling</p><p><em>Read more about Niall's business journey in <a href=\"https://businessplus.ie/news/niall-wynn-proper-order-coffee/\" target=\"_blank\" rel=\"noopener noreferrer\">Business Plus</a>.</em></p>"
  },
  {
    "id": "post-kabuto-samurai-story",
    "title": "The Samurai Kabuto Tradition & Alonzo-gan Story",
    "intro": "The history and symbolism behind our club artwork: ancient samurai Kabuto armor, the warrior philosophy of Fudoshin (immovable mind), and how it honors 1980 Olympian Sensei Alonzo Henderson 6th Dan OLY.",
    "category": "Club Heritage",
    "date": "2026-09-16",
    "dateFormatted": "September 16, 2026",
    "author": "David Moloney (Assistant Coach & Secretary)",
    "featuredImage": "images/samurai_mask_black.jpg",
    "featured": true,
    "content": "<p>The <strong>Kabuto (兜)</strong> helmet and <strong>Menpo (面頬)</strong> facial armor were the defining symbols of the ancient Japanese samurai warrior. Far beyond physical protection in combat, each Kabuto was an intricate work of art and craftsmanship designed to express the warrior's soul, lineage, and unshakable discipline on the battlefield.</p><div class=\"blog-post-img-container\" style=\"text-align: center; margin: 1.5rem 0;\"><img src=\"images/samurai_mask_black.jpg\" alt=\"Kabuto Samurai Mask Artwork with sunglasses and mustache\" style=\"max-height: 480px; width: auto; max-width: 100%; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); display: inline-block;\"><p style=\"font-size: 0.9rem; color: #6B7280; margin-top: 0.5rem; font-style: italic;\">The Cabra Kabuto: Traditional Japanese warrior helmet fused with Sensei Alonzo Henderson's signature sunglasses, mustache, and Alonzo-gan (あろんぞがん).</p></div><h3>The Philosophy of Fudoshin (不動心)</h3><p>The sculpted face mask was forged with fierce expressions to project inner strength and psychological dominance, while the crown featured an ornate <em>Maedate</em> (crest) honoring ancestral clans and sacred virtues. In martial philosophy, the helmet embodies <strong>Fudoshin (不動心)</strong>—the 'immovable mind' that remains calm, composed, and resolute in the face of pressure and adversity.</p><h3>Homage to Sensei Alonzo Henderson 6th Dan OLY</h3><p>Our new club artwork connects this legendary armor directly to our own tatami, paying homage to 1980 Olympian <strong>Sensei Alonzo Henderson 6th Dan OLY</strong>. Merging the traditional horned Kabuto with our club crest, founding year (2011), and <em>あろんぞがん (Alonzo-gan!)</em>, it celebrates over 65 years of judo mastery and the enduring fighting spirit of Cabra Judo Club.</p><div class=\"blog-gallery-grid\" style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 1.5rem 0;\"><img src=\"images/samurai_mask_white.jpg\" alt=\"Kabuto Samurai Mask White Canvas\" style=\"width: 100%; border-radius: 8px; border: 1px solid #E5E7EB;\"><img src=\"images/tshirt_black.jpg\" alt=\"Cabra Kabuto T-Shirt Black Edition\" style=\"width: 100%; border-radius: 8px; border: 1px solid #E5E7EB;\"><img src=\"images/tshirt_white.jpg\" alt=\"Cabra Kabuto T-Shirt White Edition\" style=\"width: 100%; border-radius: 8px; border: 1px solid #E5E7EB;\"><img src=\"images/cabra_katabami_crest.jpg\" alt=\"Katabami Mon Crest\" style=\"width: 100%; border-radius: 8px; border: 1px solid #E5E7EB;\"></div><h3>Official Club Apparel</h3><p>The Kabuto artwork features prominently on our official club t-shirts, available now in both Black and White editions in youth and adult sizes.</p><p><a href=\"shop.html\" class=\"shop-buy-btn\" style=\"display: inline-block; text-decoration: none; padding: 0.65rem 1.25rem; margin-top: 0.5rem;\">Order Your Kabuto T-Shirt in the Club Shop (&euro;15) &rarr;</a></p>"
  },
  {
    "id": "post-2026-09-16-tshirt",
    "title": "Official Club T-Shirts & Kabuto Samurai Graphics Unveiled",
    "intro": "Introducing our brand new Cabra Judo Club apparel featuring the iconic Kabuto samurai mask modeled on Sensei Alonzo Henderson OLY, traditional Katabami crest, and the leaping judo goat emblem.",
    "category": "Gear & Merch",
    "date": "2026-09-16",
    "dateFormatted": "September 16, 2026",
    "author": "David Moloney (L2 Coach & Secretary)",
    "featuredImage": "images/tshirt_kabuto.jpg",
    "featured": true,
    "content": "\n<p>We are delighted to reveal the official new t-shirt collection for Cabra Judo Club! Modeled around our club's fighting spirit, tradition, and community pride, the new designs are now available for all members, parents, and supporters.</p>\n\n<h3>The Kabuto Samurai Mask \u2014 Can you guess who?</h3>\n<p>The flagship t-shirt design features a Japanese <em>Kabuto</em> (\u515c) warrior helmet integrated with signature club personality: stylish sunglasses, a neat mustache, and the Japanese katakana <strong>\u3042\u308d\u3093\u305e\u304c\u3093 (Alonzo-gan!)</strong>. Modelled on none other than our Olympian head coach <strong>Sensei Alonzo Henderson 6th Dan OLY</strong>, this design pays homage to his 65 years on the tatami and Olympic pedigree.</p>\n\n<div class=\"blog-gallery-grid\" style=\"display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 1rem; margin: 1.5rem 0;\">\n  <img src=\"images/tshirt_kabuto.jpg\" alt=\"Cabra Kabuto T-Shirt\" style=\"width: 100%; border-radius: 8px; border: 1px solid #E5E7EB;\">\n  <img src=\"images/cabra_katabami_crest.jpg\" alt=\"Katabami Mon Crest\" style=\"width: 100%; border-radius: 8px; border: 1px solid #E5E7EB;\">\n  <img src=\"images/cabra_goats_emblem.png\" alt=\"Cabra G.O.A.T.s Leaping Goat\" style=\"width: 100%; border-radius: 8px; border: 1px solid #E5E7EB;\">\n</div>\n\n<h3>Available Now in the Club Shop</h3>\n<p>All three official club designs (<strong>Cabra Kabuto</strong>, <strong>Cabra Katabami</strong>, and <strong>Cabra G.O.A.T.s</strong>) are available now for just <strong>&euro;15.00</strong> each with youth (ages 5&ndash;13) and adult unisex (XS&ndash;3XL) sizes.</p>\n<p><a href=\"shop.html\" class=\"shop-buy-btn\" style=\"display: inline-block; text-decoration: none; padding: 0.65rem 1.25rem; margin-top: 0.5rem;\">Visit the Club Shop to Order (&euro;15) &rarr;</a></p>\n"
  },
  {
    "id": "4d3576ff-e9f4-4429-a2ed-759df0b15a2c",
    "title": "65 years in judo and still going strong",
    "intro": "Today our sensei Alonzo Henderson OLY celebrates 70 years of life and an astounding 65 years on the tatami. From competing at the 1980 Olympic Games in Moscow to developing hundreds of young judoka across Dublin, his dedication to the art remains unmatched.",
    "category": "Club News",
    "date": "2025-12-22",
    "dateFormatted": "December 22, 2025",
    "author": "David Moloney",
    "featuredImage": "images/blog/alonzo_65_years.png",
    "featured": true,
    "content": "<div class=\"blog-post-img-container\" style=\"text-align: center; margin: 1.5rem 0;\"><img src=\"images/blog/alonzo_65_years.png\" alt=\"Sensei Alonzo Henderson 6th Dan OLY in official Cabra Judo Club gi with 6th Dan red and white belt\" style=\"max-height: 520px; width: auto; max-width: 100%; border-radius: 8px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.1); display: inline-block;\"><p style=\"font-size: 0.9rem; color: #6B7280; margin-top: 0.5rem; font-style: italic;\">Sensei Alonzo Henderson 6th Dan OLY in official Cabra Judo Club gi and Kohaku-obi (red-and-white belt) celebrating 65 years in judo.</p></div><p>Our head coach Alonzo Henderson OLY represented Ireland in the 1980 Moscow Olympics and his competitive career reached an international high point when he secured a 5th-place finish at the 1979 World Championships in Paris, one of the most significant achievements for an Irish judoka on the world stage. Today, he holds the elite rank of 6th Dan (Rokudan), a status visually marked by the prestigious red and white paneled belt, representing over six decades of dedication to the sport.</p><p>In 2011, Henderson founded the Cabra Judo Club in Dublin, driven by a mission to bring the discipline and values of martial arts to the youth of the north inner city. With more than 35 years of coaching experience across schools and universities, he focuses on teaching the fundamental principles of judo: mutual welfare and maximum efficiency. Through the club, he provides a structured environment where students can develop physical skill and personal character, drawing from his own extensive history as both a world-class athlete and a mentor.</p><p>Beyond his technical instruction, Henderson has been a vital advocate for the sport’s development through his involvement with the Irish Judo Association. His personal trajectory, from his early life in a care home to becoming a respected leader in the international judo community, serves as a testament to the transformative power of the sport. He remains a dedicated pillar of the Irish martial arts community, continuing to guide the next generation of athletes at Cabra Judo Club toward their own success.</p><p><a href=\"staff.html\" class=\"pill-link\" style=\"margin-top: 1rem; display: inline-flex;\"><span>Read Full Coach Bio on Staff Page &rarr;</span></a></p>"
  },
  {
    "id": "3ead9d20-3d87-41d0-925f-a477d9b0c82d",
    "title": "National Judo Championships 2025",
    "intro": "A year of hard work by our judokas has yielded exceptional results",
    "category": "Competitions",
    "date": "2025-12-12",
    "dateFormatted": "2025-12-12",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/PXL_20251213_093154219-MP.jpg",
    "featured": true,
    "content": "<p>We had a total of 20 players at the national judo chamopinships in the national indoor arena in Blanchardstown on Saturday Dec 13th</p><p>We went from 1 gold, 2 silvers and 2 bronzes in 2024 to 1 gold, 4 silvers and 4 bronzes in 2025</p><div class=\"blog-post-img-container\"><img src=\"images/blog/PXL_20251214_104411007-MP.jpg\" data-width=\"100%\" data-align=\"center\"></div><p>Three medals came from our seniors Gocha (gold), Ari and Shota (bronze) and the remaining six from our minor and pre-cadet players.</p><p>The elves were with us!</p><div class=\"blog-post-img-container\"><img src=\"images/blog/PXL_20251213_063127939-MP.jpg\" data-width=\"100%\" data-align=\"center\"></div><p>And the Mums :)</p><p></p><div class=\"blog-post-img-container\"><img src=\"images/blog/PXL_20251213_093649028.jpg\" data-width=\"100%\" data-align=\"center\"></div><p></p><div class=\"blog-post-img-container\"><img src=\"images/blog/PXL_20251213_093525024-MP.jpg\" data-width=\"100%\" data-align=\"center\"></div>"
  },
  {
    "id": "f2af1236-aa00-461f-ad4e-eb283eb921e1",
    "title": "Cabra Judo Success",
    "intro": "At the Kyu/Dan Competition on Sunday Nov 16th",
    "category": "Competitions",
    "date": "2025-11-17",
    "dateFormatted": "2025-11-17",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/PXL_20251116_140309715.jpg",
    "featured": false,
    "content": "<p>Gold \ud83e\udd47 Shota, Ari</p><p>Silver \ud83e\udd48 Cristi, Ferhat</p><p>Bronze \ud83e\udd49 Teo, Octavian, Odhran</p><div class=\"blog-post-img-container\"><img src=\"images/blog/PXL_20251116_135922450.jpg\" data-width=\"100%\" data-align=\"center\"></div><p>Also at the kids competition 10 medals</p><p>4x Gold</p><p>3x Silver</p><p>2x Bronze</p><p></p>"
  },
  {
    "id": "b09cea0d-6996-4e0c-9d0d-a0ba3d134a4d",
    "title": "Happy Halloween",
    "intro": "O\u00edche Shamhna shona daoibh go l\u00e9ir.",
    "category": "Club News",
    "date": "2025-10-31",
    "dateFormatted": "2025-10-31",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/WhatsApp-Image-2025-10-31-at-10-01-14_3cef70d1.jpg",
    "featured": false,
    "content": "<p>Happy Halloween \ud83c\udf83\ud83d\udc7b</p><div class=\"blog-post-img-container\"><img src=\"images/blog/WhatsApp-Image-2025-10-31-at-10-13-13_e1a63763.jpg\" data-width=\"100%\" data-align=\"center\"></div>"
  },
  {
    "id": "fb12ac3c-c407-489d-8fb8-142b2559f51b",
    "title": "Common Randori Mistakes",
    "intro": "Mistakes in randori can be grouped into mindset, safety, and technical errors:",
    "category": "Training & Tips",
    "date": "2025-10-24",
    "dateFormatted": "2025-10-24",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/Randori-2.jpg",
    "featured": false,
    "content": "<h3>Mindset and Etiquette Mistakes</h3><ul><li><p><strong>1. Talking during Randori:</strong> Do not stop mid-sparring to ask for advice. Randori is \"playing\" Judo and requires focus. <u>All questions and analysis should be saved until </u><em><u>after</u></em><u> the round.</u></p></li><li><p><strong>2. Treating Randori as <em>Shiai</em> (Competition):</strong> Avoid being overly defensive and closed off to prevent conceding a score. <u>Randori is the time to </u><strong><u>experiment</u></strong><u>, fail, and figure out what techniques do and don't work, rather than playing it safe.</u></p></li><li><p><strong>5. Declining to do Randori:</strong> Unless you are injured or sick, never refuse a request to spar. Making progress in Judo is directly tied to the amount of Randori you do; <u>players who love sparring are the ones who improve the fastest.</u></p></li></ul><h3>Safety and Skill Adjustment Mistakes</h3><ul><li><p><strong>3. Avoiding Senior Players:</strong> Beginners should actively seek out sparring with high-level belts (brown or black belts). These experienced players are skilled enough to <strong>control the exchange and take care of you</strong>, making them safer partners than other beginners who might not know the rules or proper technique.</p></li><li><p><strong>4. Spinning out of a Throw:</strong> If you are a beginner and are being thrown, <strong>take the fall</strong> (<em>Ukemi</em>) safely. Attempting to twist or spin out of a throw to avoid a score can easily lead to serious injuries like sprained backs or broken arms.</p></li><li><p><strong>6. Fighting everyone the same way:</strong> <u>Adjust your style to your opponent.</u> Against a <strong>much larger/stronger</strong> opponent, avoid small-player techniques that will get you countered. Against a <strong>smaller/weaker</strong> partner, practice subtle techniques like <strong>Ashi Waza (foot sweeps)</strong> to adhere to the principle of \"mutual benefit\" and prevent injury.</p></li></ul><h3>Technical and Habit Mistakes</h3><ul><li><p><strong>7. Not following up in <em>Newaza</em>:</strong> If the rules allow, always transition to ground fighting (<em>Newaza</em>) after a throw or a fall. This practice must be repeated to become an <strong>automatic, instinctive habit</strong> rather than a conscious effort.</p></li><li><p><strong>8. Not attacking an <em>Uke</em> on their knees:</strong> If your opponent falls to their knees but their elbows are not on the mat, they are still considered in a standing position (<em>Tachi Waza</em>) and are extremely vulnerable. Attack immediately with a throw to capitalize on this momentary instability and build a good habit of follow-up pressure.</p></li></ul><p></p>"
  },
  {
    "id": "0311804f-223c-4981-a998-72a162706e6d",
    "title": "\ud83e\udd4b Using Randori to Improve",
    "intro": "Using randori with objectives in mind helps improve your judo more rapidly",
    "category": "Training & Tips",
    "date": "2025-10-24",
    "dateFormatted": "2025-10-24",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/How-to-fight-beginners.png",
    "featured": false,
    "content": "<p><span style=\"color: rgb(19, 19, 19)\">Ken Gunji shares 6 key ways to make your randori more meaningful and effective : </span></p><p><span style=\"color: rgb(19, 19, 19)\">1\ufe0f\u20e3 Set a small goal before you start your randori session </span><a target=\"\" rel=\"noopener noreferrer nofollow\" class=\"yt-core-attributed-string__link yt-core-attributed-string__link--call-to-action-color\" href=\"https://www.youtube.com/watch?v=wsDFpn_Yol0&amp;t=184s\"><span style=\"color: rgb(6, 95, 212)\">03:04</span></a><span style=\"color: rgb(19, 19, 19)\"> </span></p><p><span style=\"color: rgb(19, 19, 19)\">2\ufe0f\u20e3 How to feel your opponent\u2019s balance and use it to your advantage </span><a target=\"\" rel=\"noopener noreferrer nofollow\" class=\"yt-core-attributed-string__link yt-core-attributed-string__link--call-to-action-color\" href=\"https://www.youtube.com/watch?v=wsDFpn_Yol0&amp;t=234s\"><span style=\"color: rgb(6, 95, 212)\">03:54</span></a></p><p><span style=\"color: rgb(19, 19, 19)\">3\ufe0f\u20e3 How to identify who has the grip advantage \u2014 and how to change it </span><a target=\"\" rel=\"noopener noreferrer nofollow\" class=\"yt-core-attributed-string__link yt-core-attributed-string__link--call-to-action-color\" href=\"https://www.youtube.com/watch?v=wsDFpn_Yol0&amp;t=296s\"><span style=\"color: rgb(6, 95, 212)\">04:56</span></a></p><p><span style=\"color: rgb(19, 19, 19)\">4\ufe0f\u20e3 How to create timing instead of waiting for it </span><a target=\"\" rel=\"noopener noreferrer nofollow\" class=\"yt-core-attributed-string__link yt-core-attributed-string__link--call-to-action-color\" href=\"https://www.youtube.com/watch?v=wsDFpn_Yol0&amp;t=342s\"><span style=\"color: rgb(6, 95, 212)\">05:42</span></a></p><p><span style=\"color: rgb(19, 19, 19)\">5\ufe0f\u20e3 How to analyze why you were able to throw </span><a target=\"\" rel=\"noopener noreferrer nofollow\" class=\"yt-core-attributed-string__link yt-core-attributed-string__link--call-to-action-color\" href=\"https://www.youtube.com/watch?v=wsDFpn_Yol0&amp;t=385s\"><span style=\"color: rgb(6, 95, 212)\">06:25</span></a></p><p><span style=\"color: rgb(19, 19, 19)\">6\ufe0f\u20e3 How to learn faster by analyzing why you got thrown </span><a target=\"\" rel=\"noopener noreferrer nofollow\" class=\"yt-core-attributed-string__link yt-core-attributed-string__link--call-to-action-color\" href=\"https://www.youtube.com/watch?v=wsDFpn_Yol0&amp;t=428s\"><span style=\"color: rgb(6, 95, 212)\">07:08</span></a><span style=\"color: rgb(19, 19, 19)\">  </span></p><p><span style=\"color: rgb(19, 19, 19)\">These concepts will help you turn every round into a learning opportunity instead of just a fight.  </span></p><div data-youtube-video=\"\"><iframe width=\"640\" height=\"480\" allowfullscreen=\"true\" autoplay=\"false\" disablekbcontrols=\"false\" enableiframeapi=\"false\" endtime=\"0\" ivloadpolicy=\"0\" loop=\"false\" modestbranding=\"false\" origin=\"\" playlist=\"\" src=\"https://www.youtube.com/embed/wsDFpn_Yol0\" start=\"0\"></iframe></div><p></p><p></p>"
  },
  {
    "id": "923d8226-3d66-4478-911e-7d76dbcfab39",
    "title": "Our Founder Jogoro Kano's Birthday",
    "intro": "Jigoro Kano's quotes often link the principles of judo to broader life lessons",
    "category": "Club Heritage",
    "date": "2025-10-22",
    "dateFormatted": "2025-10-22",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/kano-13_orig.jpg",
    "featured": false,
    "content": "<p><span style=\"color: rgb(0, 29, 53)\">Jigoro Kano's quotes often link the principles of judo to broader life lessons of peace, mutual prosperity, and self-improvement, such as <strong><mark data-color=\"rgba(0, 0, 0, 0)\" style=\"background-color: rgba(0, 0, 0, 0); color: inherit\">\"mutual prosperity is the ideal social life\" and the idea that \"to be better than yesterday\" is more important than being better than others</mark></strong>. He taught that judo could help cultivate self-control and emotional balance, stating that \"anger is a waste of energy\"</span></p><p><strong>On peace and society</strong></p><ul><li><p>\"So, it is understood, that mutual prosperity is the ideal social life. For this reason, people must strive from childhood to try to form themselves for an ideal society, or in other words, they always have to think of others in addition to thinking of themselves so that they progress mutually; when you do it for others, do not forget that you also do it for yourself. In this way, harmony, peace, and development are born\".<span>&nbsp;</span></p></li><li><p>\"Judo is a study of techniques with which you may kill if you wish to kill, injure if you wish to injure, subdue if you wish to subdue, and, when attacked, defend yourself\".<span>&nbsp;</span></p></li></ul><p><strong>On self-improvement and mindset</strong></p><ul><li><p>\"If you win, do not boast of your victory; if you lose do not be discouraged. When it is safe, do not be careless; when it is dangerous, do not fear, simply continue down the path ahead\".<span>&nbsp;</span></p></li><li><p>\"It is not important to be better than someone else, but to be better than yesterday\".<span>&nbsp;</span></p></li><li><p>\"Judo can help such people learn to control themselves. Through training, they quickly realize that anger is a waste of energy, that it has only negative effects on the self and others\".<span>&nbsp;</span></p></li><li><p>\"In both cases there is only one road to follow\u2013the one he deems best at the time. Thus the teaching of Judo may lift a man from the depths of discouragement to vigorous activity with a bright hope in the future\".<span>&nbsp;</span></p></li></ul><p><strong>On the practice of judo</strong></p><ul><li><p>\"Apply just the right amount of force \u2014 never too much, never too little\".<span>&nbsp;</span></p></li><li><p>\"Apply Judo's principle of mutual benefit to master life's interactions\".<span>&nbsp;</span></p></li><li><p>\"In randori we learn employ the principle of maximum efficiency even when we could easily overpower an opponent\".<span>&nbsp;</span></p></li></ul><p><strong>#JudoForPeace</strong><span style=\"color: rgb(51, 51, 51)\">, </span><strong>#WJD2025Peace</strong><span style=\"color: rgb(51, 51, 51)\"> and </span><strong>#JudoIsPeaceUnityFriendship</strong><span style=\"color: rgb(51, 51, 51)\">.</span></p><div data-youtube-video=\"\"><iframe width=\"640\" height=\"480\" allowfullscreen=\"true\" autoplay=\"false\" disablekbcontrols=\"false\" enableiframeapi=\"false\" endtime=\"0\" ivloadpolicy=\"0\" loop=\"false\" modestbranding=\"false\" origin=\"\" playlist=\"\" src=\"https://www.youtube.com/embed/bZv2jzehOU0\" start=\"0\"></iframe></div>"
  },
  {
    "id": "b9a2df22-e370-4d0f-83eb-c6d3af015432",
    "title": "World Judo Day Oct 28th 2025",
    "intro": "In 2025 Judo stands for Peace, Unity and Friendship",
    "category": "Club News",
    "date": "2025-10-22",
    "dateFormatted": "2025-10-22",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/poster-1759762176-1759762176.jpg",
    "featured": true,
    "content": "<p><strong>This year\u2019s celebration of Jirgoro Kano's birthday highlights how judo builds understanding, respect and harmony across borders.</strong> </p><p>World Judo highlights the IJF\u2019s long-running Judo for Peace programme which workds with communities in conflict zones, refugee camps and developing areas, proving that judo is more than a sport, it\u2019s a force for human connection.</p><p><span style=\"color: #E00000\"><strong>In this spirit we invite all our members and anybody interest to sign up for a trial lesson on Oct 29th (Lindsay Rd), Oct 29th (Cabra) and Nov 1st (Cabra)</strong></span></p><p><strong>#JudoForPeace</strong>, <strong>#WJD2025Peace</strong> and <strong>#JudoIsPeaceUnityFriendship</strong>.</p><div class=\"blog-post-img-container\"><img src=\"images/blog/images.jpg\" data-width=\"100%\" data-align=\"center\" alt=\"Jigoro Kano Shihan Kano adapted traditional jiu-jitsu to create Judo in 1882 as an educational method focused on the principles of &quot;maximum efficiency with minimum effort&quot; (\\(seiryokuzen^{\\prime }y\u014d\\)) and &quot;mutual welfare and benefit&quot; (\\(jitaky\u014dei\\)). &nbsp;\"></div>"
  },
  {
    "id": "dcbfe0d5-c949-4462-9aab-ac2709134559",
    "title": "Home Judo Workout",
    "intro": "20 min Judo Specific Workout from Scottish International Sally Conway",
    "category": "Training & Tips",
    "date": "2025-10-20",
    "dateFormatted": "2025-10-20",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/Sally-03-1677742842-1677742842.jpg",
    "featured": false,
    "content": "<p></p><p></p><div data-youtube-video=\"\"><iframe width=\"640\" height=\"480\" allowfullscreen=\"true\" autoplay=\"false\" disablekbcontrols=\"false\" enableiframeapi=\"false\" endtime=\"0\" ivloadpolicy=\"0\" loop=\"false\" modestbranding=\"false\" origin=\"\" playlist=\"\" src=\"https://www.youtube.com/embed/Gu6m8iaw5FM\" start=\"0\"></iframe></div>"
  },
  {
    "id": "2d9aaf7c-af6a-4065-bada-66cb9066e966",
    "title": "Leinster Open 2025 Medal Success",
    "intro": "Our players won a total of 11 medals, many of them on their first outing!",
    "category": "Competitions",
    "date": "2025-10-20",
    "dateFormatted": "2025-10-20",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/LeinsterOpenWinners2025.jpg",
    "featured": true,
    "content": "<p>The 11 medals were distributed among Minor, Pre-Cadet, and Cadet divisions:</p><ul><li><p><strong>3 Silver Medals:</strong></p><ul><li><p>Minor Girls u24kg</p></li><li><p>Minor Boys u42kg (2015/2016/2017)</p></li><li><p>Pre-Cadet Boys O73kg</p></li></ul></li><li><p><strong>8 Bronze Medals:</strong></p><ul><li><p>The Bronze medals were won across a variety of age and weight categories, including Minor Girls u32kg and u40kg, Minor Boys u24kg, u38kg (two separate players in the category), u50kg, and O60kg, as well as Cadet Boys O81kg.</p></li></ul></li></ul><p></p>"
  },
  {
    "id": "243e8072-91b8-455b-be4b-22fef66697df",
    "title": "Lindsay Road First Class",
    "intro": "We had our first session in Lindsay Road NS hall today Oct 1st 2025",
    "category": "Club News",
    "date": "2025-10-01",
    "dateFormatted": "2025-10-01",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/PXL_20251008_171649159.jpg",
    "featured": false,
    "content": "<p></p>"
  },
  {
    "id": "85e326f4-26a3-4fb4-8df5-3256c36c2295",
    "title": "Irish National Schools Championships",
    "intro": "The 2025 All Ireland School Championships took place on Sunday, May 25, 2025, at the Phibblestown Community Centre in Dublin",
    "category": "Competitions",
    "date": "2025-05-25",
    "dateFormatted": "2025-05-25",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/PXL_20250607_123154166-PORTRAIT.jpg",
    "featured": false,
    "content": "<p>Cabra JC had a highly successful competition, securing a total of <strong>12 medals</strong>, which included <strong>2 Gold</strong>, <strong>2 Silver</strong>, and <strong>8 Bronze</strong>.</p><div class=\"blog-post-img-container\"><img src=\"images/blog/IMG_20250525_152104357.jpg\" data-width=\"100%\" data-align=\"center\"></div><p></p><div class=\"blog-post-img-container\"><img src=\"images/blog/PXL_20250525_130818065.jpg\" data-width=\"100%\" data-align=\"center\"></div><div class=\"blog-post-img-container\"><img src=\"images/blog/PXL_20250525_113106360-ANIMATION.gif\" data-width=\"100%\" data-align=\"center\"></div>"
  },
  {
    "id": "eaf9e6f9-906e-43bd-8e7c-c66123e69ffb",
    "title": "Our new logo",
    "intro": "Our new logo looks like a shamrock but it's traditional Japanese",
    "category": "Club Heritage",
    "date": "2025-03-17",
    "dateFormatted": "2025-03-17",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/unnamed-2-.png",
    "featured": true,
    "content": "<p><span style=\"color: rgb(33, 33, 33)\">The logo is based on the </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://www.rakuten.ne.jp/gold/kb-hayashi/kamon/30ka.html\"><span style=\"color: rgb(33, 33, 33)\"><u>Katabami</u></span></a><span style=\"color: rgb(33, 33, 33)\"> crest (kamon) and features wood sorrel leaves, symbolizing resilience and adaptability.&nbsp;</span></p><p><span style=\"color: rgb(33, 33, 33)\">The wood sorrel is prolific which speaks to the survival and prosperity of those who adopt this </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://en.wikipedia.org/wiki/Mon_(emblem)\"><span style=\"color: rgb(33, 33, 33)\"><u>kamon</u></span></a><span style=\"color: rgb(33, 33, 33)\">.&nbsp;</span></p><p><span style=\"color: rgb(33, 33, 33)\">It was&nbsp; especially favored among the </span><a target=\"_blank\" rel=\"noopener noreferrer nofollow\" href=\"https://en.wikipedia.org/wiki/Samurai\"><span style=\"color: rgb(33, 33, 33)\"><u>Samurai</u></span></a><span style=\"color: rgb(33, 33, 33)\"> warrior classes for its connotations of victory and the flourishing of one\u2019s lineage.</span></p><div class=\"blog-post-img-container\"><img src=\"images/blog/IMG_4448-scaled-e1654151408505-1024x918.jpg\" data-width=\"100%\" data-align=\"center\"></div><div class=\"blog-post-img-container\"><img src=\"images/blog/Screenshot-2025-10-20-131241.png\" data-width=\"100%\" data-align=\"center\"></div>"
  },
  {
    "id": "4fd3eb13-db07-4ae4-80f8-6c39b23a7fb0",
    "title": "Galway Open 2025",
    "intro": "Cabra JC won 7 medals at the Galway Open 2025 across Minor & Cadet divisions",
    "category": "Competitions",
    "date": "2025-03-12",
    "dateFormatted": "2025-03-12",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/PXL_20250308_111624161.jpg",
    "featured": false,
    "content": "<p></p><h3>Silver Medals (2)</h3><ul><li><p><strong>Minor Division:</strong> Silver medals were won in the Minor Boys U30kg and Minor Boys U42kg categories.</p></li></ul><h3>Bronze Medals (5)</h3><ul><li><p><strong>Cadet Division:</strong> Bronze medals were secured in the Cadet Male U55kg and Cadet Male U66kg categories.</p></li><li><p><strong>Minor Division:</strong> Bronze medals were won in the Minor Boys U42kg, Minor Boys U46kg, and Minor Girls U40 categories.</p></li></ul><div class=\"blog-post-img-container\"><img src=\"images/blog/PXL_20250308_091826301-MP.jpg\" data-width=\"100%\" data-align=\"center\"></div><div class=\"blog-post-img-container\"><img src=\"images/blog/PXL_20250308_095213298.jpg\" data-width=\"100%\" data-align=\"center\"></div>"
  },
  {
    "id": "5a90db96-636f-4454-a8ab-a38fc45a97ad",
    "title": "Irish National Judo Championships Success",
    "intro": "Our players won 1x Gold, 2x Silver & 2x Bronze in the Irish Nationals",
    "category": "Competitions",
    "date": "2024-12-14",
    "dateFormatted": "2024-12-14",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/Screenshot-2025-10-20-122057.png",
    "featured": false,
    "content": "<p>Cabra Judo Club achieved the following results at the <strong>Irish National Judo Championships 2024</strong> (<span style=\"color: rgb(31, 31, 31)\">Saturday, 14th December 2024 \ud83d\udccd Location: Sport Ireland Campus Indoor Arena</span>):</p><ul><li><p><strong>1 Gold Medal</strong></p></li><li><p><strong>2 Silver Medals</strong></p></li><li><p><strong>2 Bronze Medals</strong></p></li></ul><p></p>"
  },
  {
    "id": "fdae6f58-048f-40ab-b743-f154a40e1ad8",
    "title": "We're a diverse club",
    "intro": "Out members come from 20+ countries across the globe",
    "category": "Club News",
    "date": "2024-12-01",
    "dateFormatted": "2024-12-01",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/Screenshot-2025-10-20-115739.png",
    "featured": false,
    "content": "<p></p>"
  },
  {
    "id": "92a52dad-e263-410d-b1a0-53615c8c2869",
    "title": "Irish National Veterans 2024 Success",
    "intro": "Congrats to our Gocha Lomatadze, Irish Veterans 2x Gold on Oct 26th",
    "category": "Competitions",
    "date": "2024-10-26",
    "dateFormatted": "2024-10-26",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/Screenshot-2025-10-20-122425.png",
    "featured": false,
    "content": "<p></p>"
  },
  {
    "id": "59617e41-ec2f-4bf8-a54d-ed520608f5c4",
    "title": "Leinster Open 2024 Success",
    "intro": "Congrats to our Leinster Open silver & bronze medalists on October 6th 2024",
    "category": "Competitions",
    "date": "2024-10-06",
    "dateFormatted": "2024-10-06",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/Screenshot-2025-10-20-122823.png",
    "featured": false,
    "content": "<p></p>"
  },
  {
    "id": "7bf790d8-b71e-4ff6-9514-58cbfb583860",
    "title": "Club Grading May 2023",
    "intro": "Congratulations to all our players who Graded On May 27th",
    "category": "Club News",
    "date": "2023-05-27",
    "dateFormatted": "2023-05-27",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/Screenshot-2025-10-20-123120.png",
    "featured": false,
    "content": "<p></p>"
  },
  {
    "id": "2de12fe7-e96a-4036-ab9b-3c69ed9208ab",
    "title": "Irish Judo Club Challenge 12 May 2023",
    "intro": "Gold & Bronze\u00a0 at the Irish Judo Club Challenge in Gormanstown May 12th",
    "category": "Competitions",
    "date": "2023-05-12",
    "dateFormatted": "2023-05-12",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/Screenshot-2025-10-20-123415.png",
    "featured": false,
    "content": "<p></p>"
  },
  {
    "id": "3788e476-5e0e-4db7-a357-a8f020babdc1",
    "title": "Inter-provincials March 24th 2023",
    "intro": "Inter-provincials March 24th, silver in the pre-cadet boys u60kg category",
    "category": "Competitions",
    "date": "2023-03-24",
    "dateFormatted": "2023-03-24",
    "author": "Cabra Judo",
    "featuredImage": "images/cabra_logo.svg",
    "featured": false,
    "content": "<p></p>"
  },
  {
    "id": "5b9326c6-686e-43a2-8afc-1cc532b6b4a5",
    "title": "West of Ireland Open Jan 27th 2023",
    "intro": "Bronze in West of Ireland Open Jan 27th 2023 minor boys o46kg",
    "category": "Competitions",
    "date": "2023-01-27",
    "dateFormatted": "2023-01-27",
    "author": "Cabra Judo",
    "featuredImage": "images/blog/West.png",
    "featured": false,
    "content": "<p></p>"
  }
];
